### ISSUE TITLE
change repo name to steam-base

### ISSUE THREAD

**Issue by kevzettler** [wmark/docker-steam#1]
super confusing trying to `docker pull wmark/docker-steam`

**Comment by wmark** [comment]
This is inconsistent, yes, and I am grateful that you have taken the time to help me improve this. I will gladly go with your suggestion and rename… a thing.

Here's where I'd love to hear your ideas:

1. You use the resulting image by  
  ```docker run … wmark/steam-base …```.
2. Yet when you want to change something, you  
  ```git clone --depth=1 https://github.com/wmark/docker-steam.git```
3. … or, because this really is a mirror of my private repository:  
  ```git clone --depth=1 https://hub.blitznote.com/mark/docker-steam-base.git```

What should I rename, to what? (I use prefix »docker« for GIT repositories that serve the sole purpose of resulting in a Docker image.)

**Comment by kevzettler** [comment]
Most important thing is to keep consistent. I do prefer the `docker-` prefix. 

I guess `docker-steam` is already taken on docker hub? So that's not an option?

how about `docker-steamcmd` or `docker-steam-base` is cool I guess

**Comment by wmark** [comment]
The prefix `wmark/` on the Docker hub is my username, and cannot be removed.

Images such as `redis` or `ruby` don't have a prefix because someone at Docker (the company) has promoted those images to the »standard library«.

**Comment by kevzettler** [comment]
> The prefix wmark/ on the Docker hub is my username, and cannot be removed.

Yeah I understand that I factor that into my suggestions of 

`wmark/docker-steamcmd` or `wmark/docker-steam-base`

**Comment by wmark** [comment]
It's already `wmark/steam-base`, no need for the redundant `docker-`. On top of that I convert the Docker image using `rkt` (appc), and like to retain the runtime-neutral name.

Anyway, thanks for your suggestions! I honestly wish we could arrive at a better name.

**Comment by kevzettler** [comment]
so change the repo name to `wmark/steam-base` then
